#!/bin/bash
# List files in the current directory
echo "Current Directory:"
ls -lA
# List files in the parent directory of the working directory
echo "Parent Directory:"
ls -lA ..
# List files in the /boot directory
echo "/boot Directory:"
ls -lA /boot
