#!/bin/bash
**echo "Current Directory:"// # List files in the current directory// ls -lA
**# List files in the parent directory of the working directory
**echo "Parent Directory:"
ls -lA ..
**# List files in the /boot directory
**echo "/boot Directory:"
**ls -lA /boot
